services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    volumes:
      - "./frontend:/app"
    depends_on:
      - backend
    networks:
      - internal

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    volumes:
      - "./backend:/app"
    restart: always
    depends_on:
      - db
    networks:
      - internal

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - "./scripts/schema.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./scripts/data.sql:/docker-entrypoint-initdb.d/2.sql"
    restart: always
    networks:
      - internal

  nginx:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    restart: always
    depends_on:
      - backend
      - frontend
    ports:
      - 80:80
    networks:
      - internal

networks:
  internal:
